version: "3.7"
services:
  redis:
    image: redis:6.0.4
    ports:
      - 6379:6379
  rabbit:
    image: rabbitmq:3.8.3-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
  game:
    build:
      context: .
      dockerfile: Game/Dockerfile
      target: prod
    image: fifalaki-game:latest
    depends_on: 
      - rabbit
    healthcheck:
      test: exit 1 && curl -f http://rabbit:5672 || exit 1
      timeout: 20s
      retries: 10
  games-list:
    build:
      context: .
      dockerfile: GamesList/Dockerfile
      target: prod
    image: fifalaki-games-list:latest
    ports:
      - 5001:5001
    depends_on: 
      - rabbit
    healthcheck:
      test: exit 1 && curl -f http://rabbit:5672 || exit 1
      timeout: 20s
      retries: 10
  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
      target: prod
    image: fifalaki-gateway:latest
    ports:
      - 5002:5002
    depends_on: 
      - rabbit
    healthcheck:
      test: exit 1 && curl -f http://rabbit:5672 || exit 1
      timeout: 20s
      retries: 10
  rtm:
    build:
      context: .
      dockerfile: Rtm/Dockerfile
    image: fifalaki-rtm:latest
    env_file: Rtm/.env.docker
    ports:
      - 5010:5010
    depends_on: 
      - rabbit
    healthcheck:
      test: exit 1 && curl -f http://guest:guest@rabbit:5672/api/aliveness-test/%2F || exit 1
      timeout: 20s
      retries: 10
  words:
    build:
      context: ./Words
      dockerfile: Dockerfile
    image: fifalaki-words:latest
    env_file: Words/.env.docker
    ports:
      - 5003:5003
    depends_on:
      - redis
    healthcheck:
      test: exit 1 && curl -f http://redis:6379 || exit 1
      timeout: 20s
      retries: 10
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: fifalaki-web:latest
    env_file: web/.env.docker
    ports:
      - 5000:3000
    
