version: "3.8"
services:
  rabbit:
    image: rabbitmq:3.8.3-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
  game:
    build:
      context: .
      dockerfile: Game/Dockerfile
      target: prod
    image: fifalaki-game:latest
    depends_on: 
      - rabbit
  games-list:
    build:
      context: .
      dockerfile: GamesList/Dockerfile
      target: prod
    image: fifalaki-games-list:latest
    ports:
      - 5001:5001
    depends_on: 
      - rabbit
  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
      target: prod
    image: fifalaki-gateway:latest
    ports:
      - 5002:5002
    depends_on: 
      - rabbit
  rtm:
    build:
      context: .
      dockerfile: Rtm/Dockerfile
    image: fifalaki-rtm:latest
    env_file: Rtm/.env.docker
    ports:
      - 5010:5010
    depends_on: 
      - rabbit
    